"""
This script implements the full text search through the inverted index generated by Whoosh
"""

from whoosh.qparser import QueryParser
from whoosh import scoring
from whoosh.index import open_dir
from config import *
from utils import *
import sys


def get_top_k_docs(query_str, index_name, top_k=50):
    index = open_dir(Inv_Index_Home, indexname=index_name)
    with index.searcher(weighting=scoring.Frequency) as searcher:
        query = QueryParser("content", index.schema).parse(query_str)
        results = searcher.search(query, limit=top_k)
        return transform_result_json(results)


def transform_result_json(results):
    json_data = dict()
    json_data['runtime'] = results.runtime
    json_data['results'] = [{'fileid': result['title'], 'path': result['path'], 'text': result['textdata']}
                            for result in results]
    return json_data


def search_across_index(query_str):
    index_list = [Ground_Truth_Index_Name, Emitted_Index_Name]
    return {name: get_top_k_docs(query_str, name) for name in index_list}


if __name__ == '__main__':
    query_s = sys.argv[1]
    data = search_across_index(query_s)
    print(data)
